apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-learn-api
  namespace: kube-learn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-learn-api
  template:
    metadata:
      labels:
        app: kube-learn-api
    spec:
      containers:
        - name: kube-learn-api
          image: kube-learn-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: kube-learn-config
            - secretRef:
                name: kube-learn-db-credentials
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
