apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-learn-api
  namespace: kube-learn
spec:
  selector:
    matchLabels:
      app: kube-learn-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
