apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-learn
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh-interval: "30s"
spec:
  project: default
  source:
    # TODO: Replace with your actual git repository URL
    repoURL: https://github.com/mizo015/kube-learn.git
    targetRevision: HEAD
    path: helm/kube-learn
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-learn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
