apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-learn.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-learn.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.api.port | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
