apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-learn.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-learn.labels" . | nindent 4 }}
    {{- include "kube-learn.apiSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "kube-learn.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-learn.apiSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "kube-learn.fullname" . }}-config
            - secretRef:
                name: {{ include "kube-learn.fullname" . }}-db-credentials
          livenessProbe:
            httpGet:
              path: {{ .Values.api.livenessProbe.path }}
              port: {{ .Values.api.port }}
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbe.path }}
              port: {{ .Values.api.port }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
