apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-learn.fullname" . }}-db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-learn.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
