apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-learn.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-learn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kube-learn.apiSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.port }}
